### PR TITLE
Upgrade to React v15, prepare dist folder.

### PR DESCRIPTION
**Pull request by alexbeletsky**
Currently this package is not usable, anywhere except `browserified` environments. Best practice is to deliver a compiled version, so it can be loaded from everywhere.

**Changes:**

1. Upgrated to React v15
2. Configured babel to produce universal module in `/dist`.
3. Introduced a build step.
4. Corrected `package.json`

### CODE REVIEW

**Comment by kimmobrunfeldt** [comment]
@alexbeletsky awesome work! Are you actually doing React without any module loader(webpack or browserify)?

**Comment by alexbeletsky** [comment]
@kimmobrunfeldt I'm using `webpack`, but quite default configuration of webpack is,

```js
  module: {
    loaders: [ {
      test: /\.js$/,
      loaders: [ 'react-hot', 'babel' ],
      exclude: /node_modules/      // <-- here
    }, {
```

Means, that *imported* modules don't go through transformations (otherwise it would take ages to build the app, I guess). So, UMD is best to use as distributive.

**Comment by alexbeletsky** [comment]
@kimmobrunfeldt do you consider to put that in?

**Comment by kimmobrunfeldt** [comment]
@alexbeletsky yes definitely, I've just been investigating the browserify vs webpack difference. I don't fully understand the webpack flow, and I don't want to break the lib in browserify.

**Comment by alexbeletsky** [comment]
@kimmobrunfeldt that would be great if you test it with browserify, my expectation - it's going to be totally fine :)

**Comment by alexbeletsky** [comment]
@kimmobrunfeldt ping :)

**Comment by kimmobrunfeldt** [comment]
Sorry, this has been hanging for quite a long time. Now merged and released as https://github.com/kimmobrunfeldt/react-progressbar.js/releases/tag/0.2.0

**Pull request merged**
